id: P010626
initial_creation_type: ocr
source_metadata:
  id: bdr:W22247
  title: བཀའ་བརྒྱད་བདེ་གཤེགས་འདུས་པའི་ཆོས་སྐོར
  author: ''
  volumes:
    4f2b255a067d4682ae6cbcbc2fcd0658:
      image_group_id: I2042
      title: ''
      volume_number: 1
      total_pages: 712
    0a92a8e3b6a444309c8fec5527fda673:
      image_group_id: I2043
      title: ''
      volume_number: 2
      total_pages: 542
    08f782af0ad64c0b99cd5470232c56c8:
      image_group_id: I2044
      title: ''
      volume_number: 3
      total_pages: 566
    c4a4c35bd28641e8bdd18f03f90d4d2d:
      image_group_id: I2045
      title: ''
      volume_number: 4
      total_pages: 572
    7baa0e75518645b28346bb5ad95827b7:
      image_group_id: I2046
      title: ''
      volume_number: 5
      total_pages: 554
    903e437d881845f1a4832a216fcd811b:
      image_group_id: I2047
      title: ''
      volume_number: 6
      total_pages: 522
    c6e990c512b7469f9bcaf2c0ec4a2fc7:
      image_group_id: I2048
      title: ''
      volume_number: 7
      total_pages: 622
    9b17af352d9344f38b4e7029997659ef:
      image_group_id: I2049
      title: ''
      volume_number: 8
      total_pages: 518
    c1ce360701f148dda18f517ace905c67:
      image_group_id: I2050
      title: ''
      volume_number: 9
      total_pages: 530
    f334c6ca755947a0a2d7970ffc35abe5:
      image_group_id: I2051
      title: ''
      volume_number: 10
      total_pages: 554
    bf646410a5f14f06885414b9a122740e:
      image_group_id: I2052
      title: ''
      volume_number: 11
      total_pages: 588
    894287c03e1a460a99401c588943c51f:
      image_group_id: I2053
      title: ''
      volume_number: 12
      total_pages: 668
    fbf6705696e94c6b9f6b9a3b40666ae9:
      image_group_id: I2054
      title: ''
      volume_number: 13
      total_pages: 649
