id: I25202A40
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T15:20:13+00:00'
last_modified: '2022-06-08T16:20:28.654024+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22247
  title: བཀའ་བརྒྱད་བདེ་གཤེགས་འདུས་པའི་ཆོས་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1D9B:
      image_group_id: I2042
      title: ''
      total_pages: 712
      order: 1
      base_file: 1D9B.txt
    '9707':
      image_group_id: I2043
      title: ''
      total_pages: 542
      order: 2
      base_file: 9707.txt
    9C4C:
      image_group_id: I2044
      title: ''
      total_pages: 566
      order: 3
      base_file: 9C4C.txt
    EF23:
      image_group_id: I2045
      title: ''
      total_pages: 572
      order: 4
      base_file: EF23.txt
    0F4B:
      image_group_id: I2046
      title: ''
      total_pages: 554
      order: 5
      base_file: 0F4B.txt
    FD59:
      image_group_id: I2047
      title: ''
      total_pages: 522
      order: 6
      base_file: FD59.txt
    7E38:
      image_group_id: I2048
      title: ''
      total_pages: 622
      order: 7
      base_file: 7E38.txt
    F062:
      image_group_id: I2049
      title: ''
      total_pages: 518
      order: 8
      base_file: F062.txt
    3A0C:
      image_group_id: I2050
      title: ''
      total_pages: 530
      order: 9
      base_file: 3A0C.txt
    A499:
      image_group_id: I2051
      title: ''
      total_pages: 554
      order: 10
      base_file: A499.txt
    3E13:
      image_group_id: I2052
      title: ''
      total_pages: 588
      order: 11
      base_file: 3E13.txt
    E156:
      image_group_id: I2053
      title: ''
      total_pages: 668
      order: 12
      base_file: E156.txt
    7F60:
      image_group_id: I2054
      title: ''
      total_pages: 649
      order: 13
      base_file: 7F60.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
